# Use root/example as user/password credentials
version: '3.1'

services:   
  spring:
    build:
      context: ../airbnb-light
      dockerfile: Dockerfile
    ports:
      - 8081:8081
      - 8000:8000
    restart: "no"
    depends_on: 
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/airbnb?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: nimporte
    networks:
      - back

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      - MYSQL_ROOT_PASSWORD=nimporte
      - MYSQL_DATABASE=airbnb
    ports:
      - 3336:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
     - back

  adminer:
    image: adminer
    restart: "no"
    depends_on: 
      - db
    ports:
      - 8082:8080
    networks:
     - back

networks:
  back:

volumes:
  db-data:

