# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=nimporte
      - MYSQL_DATABASE=airbnb
    ports:
      - 3333:3306
    networks:
     - back

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
     - back
     
 spring:
    build:
      context: ../airbnb-light # Use an image built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    restart: unless-stopped
    depends_on: 
      - db
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/airbnb?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: nimporte     
    networks:
      - back
      
networks:
  back:
    driver: bridge
